export default {
  SALES_TAX: {
    SINGAPORE: .07,
    CALIFORNIA: .0906,
    NEW_YORK: .083,
    PENNSYVANIA: .0622,
    MALAYSIA: .1,
  },
  LAUNCHED_CITIES: ['Singapore', 'Pittsburgh'],
  CUSTOMER_SERVICE_EMAIL: 'adrienshen.dev@gmail.com',
  MAX_SHOPS_RETURN_CUSTOMERS: 5,
  MAX_ORDERS_MERCHANTS: 10,
  ONLINE_PAYMENTS_ENABLED: false,
  PICKUP_INTERVALS: [15, 30, 45, 60],
}
